import type { WeatherResponse, ForecastResponse, NewsResponse } from '../types';

export const mockWeather: WeatherResponse = {
  city: 'Москва',
  country: 'RU',
  temperature: 5,
  feelsLike: 2,
  humidity: 76,
  pressure: 1013,
  windSpeed: 3,
  windDirection: 180,
  clouds: 40,
  visibility: 10,
  description: 'Переменная облачность',
  icon: '02d',
  sunrise: Date.now() / 1000 - 3600,
  sunset: Date.now() / 1000 + 7200,
  timestamp: Date.now() / 1000,
};

export const mockForecast: ForecastResponse = {
  days: [
    {
      date: new Date(Date.now()).toISOString(),
      temperature: { min: 1, max: 7, day: 5 },
      description: 'Облачно',
      icon: '03d',
      humidity: 76,
      windSpeed: 3,
    },
    {
      date: new Date(Date.now() + 86400000).toISOString(),
      temperature: { min: 2, max: 8, day: 6 },
      description: 'Ясно',
      icon: '01d',
      humidity: 65,
      windSpeed: 2,
    },
    {
      date: new Date(Date.now() + 86400000 * 2).toISOString(),
      temperature: { min: 3, max: 9, day: 7 },
      description: 'Дождь',
      icon: '10d',
      humidity: 85,
      windSpeed: 5,
    },
    {
      date: new Date(Date.now() + 86400000 * 3).toISOString(),
      temperature: { min: 0, max: 5, day: 3 },
      description: 'Снег',
      icon: '13d',
      humidity: 90,
      windSpeed: 4,
    },
    {
      date: new Date(Date.now() + 86400000 * 4).toISOString(),
      temperature: { min: -2, max: 3, day: 1 },
      description: 'Облачно',
      icon: '04d',
      humidity: 80,
      windSpeed: 3,
    },
    {
      date: new Date(Date.now() + 86400000 * 5).toISOString(),
      temperature: { min: 1, max: 6, day: 4 },
      description: 'Ясно',
      icon: '01d',
      humidity: 70,
      windSpeed: 2,
    },
    {
      date: new Date(Date.now() + 86400000 * 6).toISOString(),
      temperature: { min: 2, max: 8, day: 6 },
      description: 'Переменная облачность',
      icon: '02d',
      humidity: 72,
      windSpeed: 3,
    },
  ],
};

export const mockNews: NewsResponse = {
  articles: [
    {
      title: 'Новый прорыв в квантовых вычислениях',
      description: 'Ученые объявили о создании самого мощного квантового компьютера, способного решать задачи, недоступные классическим суперкомпьютерам.',
      url: 'https://example.com/news1',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 7200000).toISOString(),
      source: { name: 'TechNews' },
    },
    {
      title: 'Запуск новой космической миссии на Марс',
      description: 'NASA объявило о запуске новой миссии по исследованию Марса с целью поиска признаков древней жизни.',
      url: 'https://example.com/news2',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 14400000).toISOString(),
      source: { name: 'Space Today' },
    },
    {
      title: 'Революция в области искусственного интеллекта',
      description: 'Новая модель ИИ демонстрирует беспрецедентные способности в понимании и генерации естественного языка.',
      url: 'https://example.com/news3',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 21600000).toISOString(),
      source: { name: 'AI Weekly' },
    },
    {
      title: 'Открытие нового вида динозавров',
      description: 'Палеонтологи обнаружили останки ранее неизвестного вида динозавров, жившего 70 миллионов лет назад.',
      url: 'https://example.com/news4',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 28800000).toISOString(),
      source: { name: 'Science Daily' },
    },
    {
      title: 'Прорыв в лечении рака',
      description: 'Новый метод иммунотерапии показал 90% эффективность в клинических испытаниях.',
      url: 'https://example.com/news5',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 36000000).toISOString(),
      source: { name: 'Medical News' },
    },
    {
      title: 'Новая технология солнечных панелей',
      description: 'Разработаны солнечные панели с эффективностью 50%, что вдвое превышает текущие показатели.',
      url: 'https://example.com/news6',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 43200000).toISOString(),
      source: { name: 'Green Tech' },
    },
    {
      title: 'Достижения в области робототехники',
      description: 'Представлен новый робот с улучшенными возможностями взаимодействия с людьми.',
      url: 'https://example.com/news7',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 50400000).toISOString(),
      source: { name: 'Robotics Weekly' },
    },
    {
      title: 'Прогресс в области биотехнологий',
      description: 'Ученые создали новый биоматериал с уникальными свойствами для медицинских применений.',
      url: 'https://example.com/news8',
      urlToImage: null,
      publishedAt: new Date(Date.now() - 57600000).toISOString(),
      source: { name: 'BioTech News' },
    },
  ],
  totalResults: 100,
  page: 1,
  pageSize: 8,
};
